ENT.Base 			= "npc_vj_hlrze_zombie"
ENT.Type 			= "ai"
ENT.PrintName 		= "Zombie Black Ops"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "Half-Life: Resurgence"