ENT.Base 			= "npc_vj_hlrze_zombie"
ENT.Type 			= "ai"
ENT.PrintName 		= "Zombie Breeder"
ENT.Author 			= "The One Epicplayer"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "Half-Life: Resurgence"